# Configuration for ssh pipeline monitoring
ssh:
  username: lgray
  hostname: cedar5.cedar.computecanada.ca
  private: True
  encoding: 'utf-8'

frequency: 5 # minutes
root: /project/rpp-chime/chime/chime_processed/
blocktypes: [test_daily]
blockrevs: [rev_00, rev_01, rev_02, rev_03, rev_04]
# blockmetrics: []
